#ifndef TERRAIN_TYPES_HPP
# define TERRAIN_TYPES_HPP

#ifdef GAME_USE_VOXEL_REGION_BACKEND

# include "../Game/game_voxel_chunk.hpp"
# include <stdint.h>

# define TERRAIN_GENERATOR_SURFACE_HEIGHT 76
# define TERRAIN_GENERATOR_SEA_LEVEL      72
# define TERRAIN_GENERATOR_WATER_BLOCK 8U
# define TERRAIN_GENERATOR_GRASS_BLOCK 1U
# define TERRAIN_GENERATOR_DIRT_BLOCK 2U
# define TERRAIN_GENERATOR_STONE_BLOCK 3U
# define TERRAIN_GENERATOR_SHRUB_BLOCK 4U
# define TERRAIN_GENERATOR_OAK_LOG_BLOCK 5U
# define TERRAIN_GENERATOR_OAK_LEAVES_BLOCK 6U
# define TERRAIN_GENERATOR_CACTUS_BLOCK 7U
# define TERRAIN_GENERATOR_BEDROCK_BLOCK 9U
# define TERRAIN_GENERATOR_SAND_BLOCK 10U
# define TERRAIN_GENERATOR_SNOW_BLOCK 11U
# define TERRAIN_GENERATOR_PERMAFROST_BLOCK 12U
# define TERRAIN_GENERATOR_CANYON_ROCK_BLOCK 13U
# define TERRAIN_GENERATOR_SLATE_BLOCK 14U
# define TERRAIN_GENERATOR_MOSS_ROCK_BLOCK 15U
# define TERRAIN_GENERATOR_COAL_ORE_BLOCK 16U
# define TERRAIN_GENERATOR_IRON_ORE_BLOCK 17U
# define TERRAIN_GENERATOR_GOLD_ORE_BLOCK 18U
# define TERRAIN_GENERATOR_GRANITE_BLOCK 19U
# define TERRAIN_GENERATOR_ANDESITE_BLOCK 20U
# define TERRAIN_GENERATOR_DIORITE_BLOCK 21U
# define TERRAIN_GENERATOR_GRAVEL_BLOCK 22U
# define TERRAIN_GENERATOR_CLAY_BLOCK 23U
# define TERRAIN_GENERATOR_OBSIDIAN_BLOCK 24U
# define TERRAIN_GENERATOR_MOSSY_STONE_BLOCK 25U
# define TERRAIN_GENERATOR_CRACKED_STONE_BLOCK 26U
# define TERRAIN_GENERATOR_LIMESTONE_BLOCK 27U
# define TERRAIN_GENERATOR_BASALT_BLOCK 28U
# define TERRAIN_GENERATOR_DIAMOND_ORE_BLOCK 29U
# define TERRAIN_GENERATOR_EMERALD_ORE_BLOCK 30U
# define TERRAIN_GENERATOR_COPPER_ORE_BLOCK 31U
# define TERRAIN_GENERATOR_PINE_LOG_BLOCK 32U
# define TERRAIN_GENERATOR_PINE_LEAVES_BLOCK 33U
# define TERRAIN_GENERATOR_BIRCH_LOG_BLOCK 34U
# define TERRAIN_GENERATOR_BIRCH_LEAVES_BLOCK 35U
# define TERRAIN_GENERATOR_ICE_BLOCK 36U
# define TERRAIN_GENERATOR_PACKED_ICE_BLOCK 37U
# define TERRAIN_GENERATOR_RED_FLOWER_BLOCK 38U
# define TERRAIN_GENERATOR_YELLOW_FLOWER_BLOCK 39U
# define TERRAIN_GENERATOR_TALL_GRASS_BLOCK 40U
# define TERRAIN_GENERATOR_FERN_BLOCK 41U
# define TERRAIN_GENERATOR_DEAD_BUSH_BLOCK 42U
# define TERRAIN_GENERATOR_RED_MUSHROOM_BLOCK 43U
# define TERRAIN_GENERATOR_BROWN_MUSHROOM_BLOCK 44U
# define TERRAIN_GENERATOR_MUSHROOM_STEM_BLOCK 45U
# define TERRAIN_GENERATOR_LILY_PAD_BLOCK 46U
# define TERRAIN_GENERATOR_SEAGRASS_BLOCK 47U
# define TERRAIN_GENERATOR_COARSE_DIRT_BLOCK 48U
# define TERRAIN_GENERATOR_PODZOL_BLOCK 49U
# define TERRAIN_GENERATOR_MUD_BLOCK 50U
# define TERRAIN_GENERATOR_FROZEN_STONE_BLOCK 51U
# define TERRAIN_GENERATOR_CHALK_BLOCK 52U
# define TERRAIN_GENERATOR_RED_SAND_BLOCK 53U
# define TERRAIN_GENERATOR_TERRACOTTA_BLOCK 54U
# define TERRAIN_GENERATOR_SALT_BLOCK 55U
# define TERRAIN_GENERATOR_VOLCANIC_ROCK_BLOCK 56U
# define TERRAIN_GENERATOR_QUARTZ_BLOCK 57U
# define TERRAIN_GENERATOR_AMETHYST_BLOCK 58U
# define TERRAIN_GENERATOR_PACKED_SNOW_BLOCK 59U
# define TERRAIN_GENERATOR_WET_SAND_BLOCK 60U
# define TERRAIN_GENERATOR_AMBER_BLOCK 61U
# define TERRAIN_GENERATOR_FROST_CRYSTAL_BLOCK 62U
# define TERRAIN_GENERATOR_SHIMMER_STONE_BLOCK 63U
# define TERRAIN_RUNTIME_BLOCK_CAPACITY 256U
# define TERRAIN_RUNTIME_MAX_ASSET_SIZE (4U * 1024U * 1024U)
# define TERRAIN_BIOME_ZONE_WIDTH 128
# define TERRAIN_BIOME_SIZE_MINIMUM 16
# define TERRAIN_BIOME_SIZE_MAXIMUM 32768
# define TERRAIN_MAX_CUSTOM_BIOMES 16U
# define TERRAIN_MAX_FEATURE_RULES 16U
# define TERRAIN_MAX_ORE_RULES 32U
# define TERRAIN_MAX_TREE_TEMPLATES 64U
# define TERRAIN_MAX_BIOME_TREE_TEMPLATES 16U
# define TERRAIN_MAX_TREE_TEMPLATE_BLOCKS 32U
# define TERRAIN_GENERATOR_VERSION 5U
# define TERRAIN_STAGE_BASE_TERRAIN 1U
# define TERRAIN_STAGE_CAVES 2U
# define TERRAIN_STAGE_FLUIDS 4U
# define TERRAIN_STAGE_DECORATION 8U
# define TERRAIN_STAGE_STRUCTURES 16U
# define TERRAIN_STAGE_ORES 32U

enum terrain_builtin_block_id : uint32_t
{
    TERRAIN_GENERATOR_AIR_BLOCK = 0U,
    TERRAIN_GENERATOR_GRASS_BLOCK_ID = TERRAIN_GENERATOR_GRASS_BLOCK,
    TERRAIN_GENERATOR_DIRT_BLOCK_ID = TERRAIN_GENERATOR_DIRT_BLOCK,
    TERRAIN_GENERATOR_STONE_BLOCK_ID = TERRAIN_GENERATOR_STONE_BLOCK,
    TERRAIN_GENERATOR_SHRUB_BLOCK_ID = TERRAIN_GENERATOR_SHRUB_BLOCK,
    TERRAIN_GENERATOR_OAK_LOG_BLOCK_ID = TERRAIN_GENERATOR_OAK_LOG_BLOCK,
    TERRAIN_GENERATOR_OAK_LEAVES_BLOCK_ID = TERRAIN_GENERATOR_OAK_LEAVES_BLOCK,
    TERRAIN_GENERATOR_CACTUS_BLOCK_ID = TERRAIN_GENERATOR_CACTUS_BLOCK,
    TERRAIN_GENERATOR_WATER_BLOCK_ID = TERRAIN_GENERATOR_WATER_BLOCK,
    TERRAIN_GENERATOR_BEDROCK_BLOCK_ID = TERRAIN_GENERATOR_BEDROCK_BLOCK,
    TERRAIN_GENERATOR_SAND_BLOCK_ID = TERRAIN_GENERATOR_SAND_BLOCK,
    TERRAIN_GENERATOR_SNOW_BLOCK_ID = TERRAIN_GENERATOR_SNOW_BLOCK,
    TERRAIN_GENERATOR_PERMAFROST_BLOCK_ID = TERRAIN_GENERATOR_PERMAFROST_BLOCK,
    TERRAIN_GENERATOR_CANYON_ROCK_BLOCK_ID = TERRAIN_GENERATOR_CANYON_ROCK_BLOCK,
    TERRAIN_GENERATOR_SLATE_BLOCK_ID = TERRAIN_GENERATOR_SLATE_BLOCK,
    TERRAIN_GENERATOR_MOSS_ROCK_BLOCK_ID = TERRAIN_GENERATOR_MOSS_ROCK_BLOCK,
    TERRAIN_GENERATOR_COAL_ORE_BLOCK_ID = TERRAIN_GENERATOR_COAL_ORE_BLOCK,
    TERRAIN_GENERATOR_IRON_ORE_BLOCK_ID = TERRAIN_GENERATOR_IRON_ORE_BLOCK,
    TERRAIN_GENERATOR_GOLD_ORE_BLOCK_ID = TERRAIN_GENERATOR_GOLD_ORE_BLOCK,
    TERRAIN_GENERATOR_GRANITE_BLOCK_ID = TERRAIN_GENERATOR_GRANITE_BLOCK,
    TERRAIN_GENERATOR_ANDESITE_BLOCK_ID = TERRAIN_GENERATOR_ANDESITE_BLOCK,
    TERRAIN_GENERATOR_DIORITE_BLOCK_ID = TERRAIN_GENERATOR_DIORITE_BLOCK,
    TERRAIN_GENERATOR_GRAVEL_BLOCK_ID = TERRAIN_GENERATOR_GRAVEL_BLOCK,
    TERRAIN_GENERATOR_CLAY_BLOCK_ID = TERRAIN_GENERATOR_CLAY_BLOCK,
    TERRAIN_GENERATOR_OBSIDIAN_BLOCK_ID = TERRAIN_GENERATOR_OBSIDIAN_BLOCK,
    TERRAIN_GENERATOR_MOSSY_STONE_BLOCK_ID = TERRAIN_GENERATOR_MOSSY_STONE_BLOCK,
    TERRAIN_GENERATOR_CRACKED_STONE_BLOCK_ID = TERRAIN_GENERATOR_CRACKED_STONE_BLOCK,
    TERRAIN_GENERATOR_LIMESTONE_BLOCK_ID = TERRAIN_GENERATOR_LIMESTONE_BLOCK,
    TERRAIN_GENERATOR_BASALT_BLOCK_ID = TERRAIN_GENERATOR_BASALT_BLOCK,
    TERRAIN_GENERATOR_DIAMOND_ORE_BLOCK_ID = TERRAIN_GENERATOR_DIAMOND_ORE_BLOCK,
    TERRAIN_GENERATOR_EMERALD_ORE_BLOCK_ID = TERRAIN_GENERATOR_EMERALD_ORE_BLOCK,
    TERRAIN_GENERATOR_COPPER_ORE_BLOCK_ID = TERRAIN_GENERATOR_COPPER_ORE_BLOCK,
    TERRAIN_GENERATOR_PINE_LOG_BLOCK_ID = TERRAIN_GENERATOR_PINE_LOG_BLOCK,
    TERRAIN_GENERATOR_PINE_LEAVES_BLOCK_ID = TERRAIN_GENERATOR_PINE_LEAVES_BLOCK,
    TERRAIN_GENERATOR_BIRCH_LOG_BLOCK_ID = TERRAIN_GENERATOR_BIRCH_LOG_BLOCK,
    TERRAIN_GENERATOR_BIRCH_LEAVES_BLOCK_ID = TERRAIN_GENERATOR_BIRCH_LEAVES_BLOCK,
    TERRAIN_GENERATOR_ICE_BLOCK_ID = TERRAIN_GENERATOR_ICE_BLOCK,
    TERRAIN_GENERATOR_PACKED_ICE_BLOCK_ID = TERRAIN_GENERATOR_PACKED_ICE_BLOCK,
    TERRAIN_GENERATOR_RED_FLOWER_BLOCK_ID = TERRAIN_GENERATOR_RED_FLOWER_BLOCK,
    TERRAIN_GENERATOR_YELLOW_FLOWER_BLOCK_ID = TERRAIN_GENERATOR_YELLOW_FLOWER_BLOCK,
    TERRAIN_GENERATOR_TALL_GRASS_BLOCK_ID = TERRAIN_GENERATOR_TALL_GRASS_BLOCK,
    TERRAIN_GENERATOR_FERN_BLOCK_ID = TERRAIN_GENERATOR_FERN_BLOCK,
    TERRAIN_GENERATOR_DEAD_BUSH_BLOCK_ID = TERRAIN_GENERATOR_DEAD_BUSH_BLOCK,
    TERRAIN_GENERATOR_RED_MUSHROOM_BLOCK_ID = TERRAIN_GENERATOR_RED_MUSHROOM_BLOCK,
    TERRAIN_GENERATOR_BROWN_MUSHROOM_BLOCK_ID = TERRAIN_GENERATOR_BROWN_MUSHROOM_BLOCK,
    TERRAIN_GENERATOR_MUSHROOM_STEM_BLOCK_ID = TERRAIN_GENERATOR_MUSHROOM_STEM_BLOCK,
    TERRAIN_GENERATOR_LILY_PAD_BLOCK_ID = TERRAIN_GENERATOR_LILY_PAD_BLOCK,
    TERRAIN_GENERATOR_SEAGRASS_BLOCK_ID = TERRAIN_GENERATOR_SEAGRASS_BLOCK,
    TERRAIN_GENERATOR_COARSE_DIRT_BLOCK_ID = TERRAIN_GENERATOR_COARSE_DIRT_BLOCK,
    TERRAIN_GENERATOR_PODZOL_BLOCK_ID = TERRAIN_GENERATOR_PODZOL_BLOCK,
    TERRAIN_GENERATOR_MUD_BLOCK_ID = TERRAIN_GENERATOR_MUD_BLOCK,
    TERRAIN_GENERATOR_FROZEN_STONE_BLOCK_ID = TERRAIN_GENERATOR_FROZEN_STONE_BLOCK,
    TERRAIN_GENERATOR_CHALK_BLOCK_ID = TERRAIN_GENERATOR_CHALK_BLOCK,
    TERRAIN_GENERATOR_RED_SAND_BLOCK_ID = TERRAIN_GENERATOR_RED_SAND_BLOCK,
    TERRAIN_GENERATOR_TERRACOTTA_BLOCK_ID = TERRAIN_GENERATOR_TERRACOTTA_BLOCK,
    TERRAIN_GENERATOR_SALT_BLOCK_ID = TERRAIN_GENERATOR_SALT_BLOCK,
    TERRAIN_GENERATOR_VOLCANIC_ROCK_BLOCK_ID = TERRAIN_GENERATOR_VOLCANIC_ROCK_BLOCK,
    TERRAIN_GENERATOR_QUARTZ_BLOCK_ID = TERRAIN_GENERATOR_QUARTZ_BLOCK,
    TERRAIN_GENERATOR_AMETHYST_BLOCK_ID = TERRAIN_GENERATOR_AMETHYST_BLOCK,
    TERRAIN_GENERATOR_PACKED_SNOW_BLOCK_ID = TERRAIN_GENERATOR_PACKED_SNOW_BLOCK,
    TERRAIN_GENERATOR_WET_SAND_BLOCK_ID = TERRAIN_GENERATOR_WET_SAND_BLOCK,
    TERRAIN_GENERATOR_AMBER_BLOCK_ID = TERRAIN_GENERATOR_AMBER_BLOCK,
    TERRAIN_GENERATOR_FROST_CRYSTAL_BLOCK_ID = TERRAIN_GENERATOR_FROST_CRYSTAL_BLOCK,
    TERRAIN_GENERATOR_SHIMMER_STONE_BLOCK_ID = TERRAIN_GENERATOR_SHIMMER_STONE_BLOCK,
    TERRAIN_BUILTIN_BLOCK_COUNT = 64U
};

static_assert(static_cast<uint64_t>(TERRAIN_BUILTIN_BLOCK_COUNT)
        + static_cast<uint64_t>(TERRAIN_RUNTIME_BLOCK_CAPACITY)
        <= static_cast<uint64_t>(UINT32_MAX),
    "terrain block ID range exceeds uint32_t");

enum terrain_biome
{
    TERRAIN_BIOME_PLAINS = 0,
    TERRAIN_BIOME_HILLS = 1,
    TERRAIN_BIOME_DESERT = 2,
    TERRAIN_BIOME_SNOW = 3,
    TERRAIN_BIOME_MOUNTAINS = 4
};

enum terrain_json_file_mode
{
    TERRAIN_JSON_FILE_CREATE_ONLY = 0,
    TERRAIN_JSON_FILE_REPLACE = 1
};

#ifdef LIBFT_TEST_BUILD
enum terrain_json_test_file_operation
{
    TERRAIN_JSON_TEST_FILE_OPEN_CREATE_ONLY = 1,
    TERRAIN_JSON_TEST_FILE_OPEN_REPLACE = 2,
    TERRAIN_JSON_TEST_FILE_FIRST_WRITE = 3,
    TERRAIN_JSON_TEST_FILE_PARTIAL_WRITE = 4,
    TERRAIN_JSON_TEST_FILE_INTERRUPTED_WRITE = 5,
    TERRAIN_JSON_TEST_FILE_CLOSE = 6
};

int32_t terrain_json_test_fail_file_operation(
    terrain_json_test_file_operation operation, int32_t error_code,
    ft_size_t partial_write_after) noexcept;
void terrain_json_test_clear_file_failure(void) noexcept;
#endif

struct terrain_biome_profile
{
    int32_t surface_height;
    int32_t height_variation;
    int32_t topsoil_depth;
};

struct terrain_block_metadata
{
    ft_bool solid;
    ft_bool transparent;
    ft_bool liquid;
    ft_bool replaceable;
    ft_bool light_emitting;
    ft_bool occludes_faces;
    uint32_t hardness;
    ft_bool breakable;
    ft_bool can_host_ore = FT_FALSE;
    ft_bool is_ore = FT_FALSE;
};

enum terrain_block_asset_face
{
    TERRAIN_BLOCK_ASSET_FACE_TOP = 0,
    TERRAIN_BLOCK_ASSET_FACE_BOTTOM = 1,
    TERRAIN_BLOCK_ASSET_FACE_NORTH = 2,
    TERRAIN_BLOCK_ASSET_FACE_SOUTH = 3,
    TERRAIN_BLOCK_ASSET_FACE_EAST = 4,
    TERRAIN_BLOCK_ASSET_FACE_WEST = 5,
    TERRAIN_BLOCK_ASSET_FACE_COUNT = 6
};

struct terrain_block_registration
{
    const char *name;
    terrain_block_metadata metadata;
    const char *asset_paths[TERRAIN_BLOCK_ASSET_FACE_COUNT];
};

struct terrain_tree_template_block
{
    int32_t offset_x;
    int32_t offset_y;
    int32_t offset_z;
    uint32_t block_id;
};

struct terrain_tree_template
{
    const terrain_tree_template_block *blocks;
    uint32_t block_count;
};

#endif

#endif
