assert(os == nil)
assert(io == nil)
assert(debug == nil)
assert(loadfile == nil)
assert(load == nil)
assert(collectgarbage == nil)
assert(require == nil)
assert(package == nil)
assert(coroutine == nil)
capture_value(7)
