TARGET_DIR := build
TARGET_NAME := demo_dumb_game
TARGET_SUFFIX :=
ifeq ($(OS),Windows_NT)
    TARGET_SUFFIX := .exe
endif
TARGET := $(TARGET_DIR)/$(TARGET_NAME)$(TARGET_SUFFIX)
LEGACY_TARGET := $(TARGET_NAME)$(TARGET_SUFFIX)
MODULE_NAME := $(notdir $(CURDIR))
